% RUN_PHASE5_TIME_DOMAIN_CHECK Verify the three representative step cases.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'scripts'));
resultFile = fullfile(projectRoot, 'results', ...
    'phase5_time_domain_validation.mat');
needsRun = ~isfile(resultFile);
if ~needsRun
    savedNames = who('-file', resultFile);
    needsRun = ~ismember('studyResult', savedNames);
end
if needsRun
    run_time_domain_validation(resultFile);
end
saved = load(resultFile, 'studyResult');
studyResult = saved.studyResult;
cases = studyResult.cases;

assert(numel(cases) == 3, ...
    'Time-domain validation must contain exactly three cases.');
assert(isequal(string({cases.label}), ["Case A" "Case B" "Case C"]), ...
    'The representative case labels are incorrect.');
assert(isequal([cases.scr], [10 3 2]) && ...
    isequal([cases.pll_scale], [1 1 2]), ...
    'The prescribed SCR/PLL representative points are incorrect.');
assert(studyResult.configuration.final_active_power_W - ...
    studyResult.configuration.initial_active_power_W == 50e3, ...
    'Every case must use the common 50 kW active-power step.');

for k = 1:numel(cases)
    item = cases(k);
    metrics = item.metrics;
    signals = item.signals;
    assert(all(isfinite(signals.p_W)) && ...
        all(isfinite(signals.pll_frequency_Hz)), ...
        'A time-domain trace contains non-finite values.');
    assert(all(diff(signals.time_s) > 0), ...
        'A saved time vector is not strictly increasing.');
    assert(max(signals.fault_state) < 0.5, ...
        'A small reference step unexpectedly activated the physical fault.');
    assert(min(signals.soc_pu) > 0.10 && max(signals.soc_pu) < 0.90, ...
        'A representative case left the configured SoC operating band.');
    assert(isfinite(metrics.overshoot_percent) && ...
        metrics.overshoot_percent >= 0, ...
        'The overshoot metric is invalid.');
    assert(isfinite(metrics.settling_time_s) && ...
        metrics.settling_time_s >= 0 && ...
        metrics.settling_time_s <= ...
        studyResult.configuration.stop_time_s - ...
        studyResult.configuration.step_time_s, ...
        'The settling-time metric is invalid.');
    assert(isfinite(metrics.dominant_oscillation_frequency_Hz) && ...
        metrics.dominant_oscillation_frequency_Hz >= 0.5 && ...
        metrics.dominant_oscillation_frequency_Hz <= 100, ...
        'The dominant oscillation frequency is outside the analysis band.');
    assert(isfinite(metrics.oscillation_decay_ratio) && ...
        metrics.oscillation_decay_ratio >= 0, ...
        'The oscillation decay ratio is invalid.');
    assert(abs(metrics.measured_active_power_change_W) >= 5e3, ...
        'The active-power step did not produce a measurable response.');
    assert(isfinite(item.frequency_risk_score) && ...
        item.frequency_risk_score >= 0, ...
        'A representative case lacks its frequency-domain risk score.');
end

assert(isfile(fullfile(projectRoot, 'results', ...
    'phase5_time_domain_validation.png')), ...
    'The time-domain comparison plot is missing.');
fprintf('PHASE 5 TIME-DOMAIN CHECK PASS | %d representative cases\n', ...
    numel(cases));
for k = 1:numel(cases)
    item = cases(k);
    fprintf(['  %s | SCR %g PLL %.3g | risk %.6g %s | ' ...
        'overshoot %.4g%% | settling %.4g s | oscillation %.4g Hz | ' ...
        'decay %.4g %s\n'], item.label, item.scr, item.pll_scale, ...
        item.frequency_risk_score, item.frequency_risk_level, ...
        item.metrics.overshoot_percent, item.metrics.settling_time_s, ...
        item.metrics.dominant_oscillation_frequency_Hz, ...
        item.metrics.oscillation_decay_ratio, ...
        item.metrics.damping_behaviour);
end
