% RUN_PHASE1_BASELINE_EQUIVALENCE_CHECK Compare project-one baseline signals.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'scripts'));
referenceModelFile = fullfile(fileparts(projectRoot), ...
    'grid-connected-bess-control-validation', 'models', ...
    'bess_final_physical_validation.slx');
resultFile = fullfile(projectRoot, 'results', ...
    'phase1_baseline_equivalence.mat');
if ~isfile(resultFile)
    run_baseline_equivalence(referenceModelFile, resultFile);
end
saved = load(resultFile, 'studyResult');
studyResult = saved.studyResult;

assert(~studyResult.perturbation_enabled, ...
    'The baseline-equivalence comparison must disable perturbations.');
assert(numel(studyResult.signal_metrics) == 9, ...
    'The baseline comparison must cover all nine required signals.');
assert(all([studyResult.signal_metrics.passed]), ...
    'At least one baseline signal exceeds its equivalence limit.');
assert(studyResult.maximum_relative_rms_error <= ...
    studyResult.thresholds.relative_rms_error, ...
    'The baseline relative RMS error exceeds its fixed limit.');
assert(studyResult.maximum_normalized_error <= ...
    studyResult.thresholds.normalized_maximum_error, ...
    'The baseline normalized maximum error exceeds its fixed limit.');
assert(studyResult.passed, 'The project-one baseline equivalence check failed.');
fprintf(['PHASE 1 BASELINE EQUIVALENCE CHECK PASS | byte identical %d | ' ...
    'relative RMS %.6g | normalized maximum %.6g\n'], ...
    studyResult.model_files_byte_identical, ...
    studyResult.maximum_relative_rms_error, ...
    studyResult.maximum_normalized_error);
