% RUN_PHASE3_SCR_INTERACTION_CHECK Verify SCR sweep and risk scoring.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'scripts'));
resultFile = fullfile(projectRoot, 'results', 'phase3_scr_interaction.mat');
needsRun = ~isfile(resultFile);
if ~needsRun
    savedNames = who('-file', resultFile);
    needsRun = ~ismember('studyResult', savedNames);
end
if needsRun
    run_scr_interaction_scan([], resultFile);
end
saved = load(resultFile, 'studyResult');
studyResult = saved.studyResult;

assert(isequal(studyResult.scr_values, [10 5 3 2]), ...
    'The SCR sweep must contain 10, 5, 3, and 2.');
assert(studyResult.pll_scale == 1.0, ...
    'The stage-three sweep must use the nominal PLL gain.');
assert(numel(studyResult.frequency_Hz) == 20 && ...
    abs(studyResult.frequency_Hz(1)-0.5) < 1e-12 && ...
    abs(studyResult.frequency_Hz(end)-100) < 1e-12, ...
    'Every SCR case must use 20 points over 0.5 to 100 Hz.');
assert(studyResult.thresholds.moderate == 0.5 && ...
    studyResult.thresholds.higher == 1.0, ...
    'Interaction thresholds must remain fixed across all cases.');

allowedLevels = {'Lower','Moderate','Higher'};
for k = 1:numel(studyResult.cases)
    item = studyResult.cases(k);
    expectedShortCircuitPower = item.scr * ...
        item.scan.configuration.converter_base_power_VA;
    assert(all(item.scan.completed), 'An SCR scan is incomplete.');
    assert(item.scan.configuration.scr == item.scr, ...
        'The saved scan SCR does not match its case.');
    assert(abs(item.scan.configuration.grid_short_circuit_power_VA - ...
        expectedShortCircuitPower) <= eps(expectedShortCircuitPower), ...
        'Short-circuit power is inconsistent with SCR and base power.');
    assert(all(isfinite(real(item.scan.Y_dq_S)), 'all') && ...
        all(isfinite(imag(item.scan.Y_dq_S)), 'all'), ...
        'An identified dq admittance contains non-finite values.');
    assert(all(item.scan.voltage_matrix_condition < ...
        item.scan.configuration.maximum_voltage_matrix_condition), ...
        'An SCR scan contains an ill-conditioned voltage matrix.');
    assert(all(item.scan.maximum_fault_state < 0.5), ...
        'An SCR scan unexpectedly activated the physical fault.');
    assert(all(item.scan.minimum_soc_pu > 0.10) && ...
        all(item.scan.maximum_soc_pu < 0.90), ...
        'An SCR scan left the configured SoC operating band.');
    assert(all(isfinite(item.metric.interaction_gain)) && ...
        all(item.metric.interaction_gain >= 0), ...
        'The interaction metric is invalid.');
    assert(item.metric.critical_frequency_Hz >= 0.5 && ...
        item.metric.critical_frequency_Hz <= 100, ...
        'The critical frequency is outside the scan range.');
    assert(ismember(item.metric.risk_level, allowedLevels), ...
        'The risk level is not recognized.');
end

fprintf('PHASE 3 SCR INTERACTION CHECK PASS | %d SCR cases | %d injection runs\n', ...
    numel(studyResult.cases), ...
    2*numel(studyResult.cases)*numel(studyResult.frequency_Hz));
for k = 1:numel(studyResult.cases)
    item = studyResult.cases(k);
    fprintf('  SCR %g | peak %.6g | critical %.6g Hz | %s\n', ...
        item.scr, item.metric.peak_interaction_gain, ...
        item.metric.critical_frequency_Hz, item.metric.risk_level);
end
