% RUN_ALL_CHECKS Execute the complete local validation sequence.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
checks = { ...
    'run_phase1_interface_check.m', ...
    'run_phase1_repeatability_check.m', ...
    'run_phase1_baseline_equivalence_check.m', ...
    'run_phase2_frequency_scan_check.m', ...
    'run_phase3_scr_interaction_check.m', ...
    'run_phase4_pll_risk_map_check.m', ...
    'run_phase5_time_domain_check.m'};

for k = 1:numel(checks)
    run(fullfile(projectRoot, 'tests', checks{k}));
end
fprintf('ALL LOCAL CHECKS PASS | %d check groups\n', numel(checks));
