% RUN_PHASE1_REPEATABILITY_CHECK Verify independent 10 Hz scan agreement.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'scripts'));
resultFile = fullfile(projectRoot, 'results', 'phase1_repeatability.mat');
if ~isfile(resultFile)
    run_frequency_scan_repeatability(resultFile, false);
end
saved = load(resultFile, 'studyResult');
studyResult = saved.studyResult;

assert(studyResult.frequency_Hz == 10, ...
    'The repeatability reference frequency must be 10 Hz.');
assert(all(isfinite(studyResult.magnitude_relative_difference),'all') && ...
    all(isfinite(studyResult.phase_difference_deg),'all'), ...
    'A repeatability comparison contains non-finite values.');
assert(studyResult.maximum_magnitude_relative_difference <= ...
    studyResult.thresholds.admittance_magnitude_relative_difference, ...
    'The repeated admittance magnitude drift exceeds its fixed limit.');
assert(studyResult.maximum_phase_difference_deg <= ...
    studyResult.thresholds.admittance_phase_difference_deg, ...
    'The repeated admittance phase drift exceeds its fixed limit.');
assert(studyResult.passed, 'The independent 10 Hz repeatability check failed.');
fprintf(['PHASE 1 REPEATABILITY CHECK PASS | magnitude drift %.6g | ' ...
    'phase drift %.6g deg\n'], ...
    studyResult.maximum_magnitude_relative_difference, ...
    studyResult.maximum_phase_difference_deg);
