% RUN_PHASE1_INTERFACE_CHECK Verify the single-frequency interface result.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
resultFile = fullfile(projectRoot, 'results', 'phase1_single_frequency_demo.mat');
if ~isfile(resultFile)
    run(fullfile(projectRoot, 'scripts', 'run_single_frequency_demo.m'));
end
load(resultFile, 'phase1_result');

assert(isfinite(phase1_result.summary.d_axis_delta_vd_peak_to_peak_V) && ...
    phase1_result.summary.d_axis_delta_vd_peak_to_peak_V > 5, ...
    'The d-axis injection did not create a measurable PCC d-axis voltage response.');
assert(isfinite(phase1_result.summary.q_axis_delta_vq_peak_to_peak_V) && ...
    phase1_result.summary.q_axis_delta_vq_peak_to_peak_V > 5, ...
    'The q-axis injection did not create a measurable PCC q-axis voltage response.');
assert(abs(phase1_result.summary.baseline_pll_frequency_mean_Hz - 50) < 0.5, ...
    'The baseline PLL frequency is outside the nominal verification band.');
assert(phase1_result.summary.maximum_fault_state < 0.5, ...
    'A small-signal interface test unexpectedly activated the physical fault.');
assert(phase1_result.summary.minimum_soc_pu > 0.10 && ...
    phase1_result.summary.maximum_soc_pu < 0.90, ...
    'A small-signal interface test left the configured SoC operating band.');
fprintf('PHASE 1 INTERFACE CHECK PASS\\n');
