% RUN_PHASE2_FREQUENCY_SCAN_CHECK Verify the complete nominal dq scan.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'scripts'));
resultFile = fullfile(projectRoot, 'results', 'phase2_frequency_scan.mat');
run(fullfile(projectRoot, 'scripts', 'init_frequency_scan.m'));
expectedSignature = frequency_scan_case_signature(scan_cfg);
needsRun = ~isfile(resultFile);
if ~needsRun
    saved = load(resultFile, 'scanResult');
    canReassess = isfield(saved.scanResult, 'fit_quality_passed') && ...
        isfield(saved.scanResult, 'maximum_main_voltage_fit_residual') && ...
        isfield(saved.scanResult, 'maximum_current_weighted_fit_residual') && ...
        isfield(saved.scanResult, 'maximum_cross_voltage_leakage_ratio') && ...
        all(saved.scanResult.completed);
    signatureMatches = isfield(saved.scanResult, 'case_signature') && ...
        strcmp(saved.scanResult.case_signature, expectedSignature);
    if canReassess && ~signatureMatches
        scanResult = reassess_frequency_scan_quality(saved.scanResult, scan_cfg);
        save(resultFile, 'scanResult');
        signatureMatches = true;
    end
    needsRun = ~canReassess || ~signatureMatches;
end
if needsRun
    run_frequency_scan([], resultFile);
end
saved = load(resultFile, 'scanResult');
scanResult = saved.scanResult;
qualityLimits = scanResult.configuration.fit_quality_thresholds;

assert(numel(scanResult.frequency_Hz) == 20, ...
    'The nominal scan must contain 20 frequency points.');
assert(abs(scanResult.frequency_Hz(1)-0.5) < 1e-12 && ...
    abs(scanResult.frequency_Hz(end)-100) < 1e-12, ...
    'The nominal scan must cover 0.5 to 100 Hz.');
assert(all(scanResult.completed), 'At least one frequency point is incomplete.');
assert(all(isfinite(real(scanResult.Y_dq_S)), 'all') && ...
    all(isfinite(imag(scanResult.Y_dq_S)), 'all'), ...
    'The identified dq admittance contains non-finite values.');
assert(all(scanResult.voltage_matrix_condition < ...
    scanResult.configuration.maximum_voltage_matrix_condition), ...
    'At least one frequency point has an ill-conditioned voltage matrix.');
assert(all(scanResult.maximum_fault_state < 0.5), ...
    'A frequency-scan injection unexpectedly activated the physical fault.');
assert(all(scanResult.fit_quality_passed), ...
    'At least one nominal frequency point failed the fixed fit-quality gate.');
assert(all(scanResult.maximum_main_voltage_fit_residual <= ...
    qualityLimits.main_voltage_relative_residual), ...
    'A nominal point exceeds the main-voltage fit-residual limit.');
assert(all(scanResult.maximum_current_weighted_fit_residual <= ...
    qualityLimits.current_matrix_weighted_residual), ...
    'A nominal point exceeds the weighted current-response residual limit.');
assert(all(scanResult.maximum_cross_voltage_leakage_ratio <= ...
    qualityLimits.cross_voltage_leakage_ratio), ...
    'A nominal point exceeds the cross-voltage leakage limit.');
assert(all(scanResult.minimum_soc_pu > 0.10) && ...
    all(scanResult.maximum_soc_pu < 0.90), ...
    'A frequency-scan injection left the configured SoC operating band.');
fprintf('PHASE 2 FREQUENCY SCAN CHECK PASS | %d points | %d injection runs\n', ...
    numel(scanResult.frequency_Hz), 2*numel(scanResult.frequency_Hz));
