% RUN_PHASE4_PLL_RISK_MAP_CHECK Verify the complete SCR-by-PLL matrix.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'scripts'));
resultFile = fullfile(projectRoot, 'results', 'phase4_pll_risk_map.mat');
needsRun = ~isfile(resultFile);
if ~needsRun
    savedNames = who('-file', resultFile);
    needsRun = ~ismember('studyResult', savedNames);
end
if needsRun
    run_pll_risk_map([], resultFile);
end
saved = load(resultFile, 'studyResult');
studyResult = saved.studyResult;

assert(isequal(studyResult.scr_values, [10 5 3 2]), ...
    'The SCR dimension must contain 10, 5, 3, and 2.');
assert(isequal(studyResult.pll_scales, [0.5 1 1.5 2]), ...
    'The PLL dimension must contain 0.5, 1, 1.5, and 2.');
assert(isequal(size(studyResult.cases), [4 4]), ...
    'The risk map must contain sixteen cases.');
assert(numel(studyResult.frequency_Hz) == 20 && ...
    abs(studyResult.frequency_Hz(1)-0.5) < 1e-12 && ...
    abs(studyResult.frequency_Hz(end)-100) < 1e-12, ...
    'Every matrix case must cover 20 points from 0.5 to 100 Hz.');
assert(studyResult.total_matrix_injection_runs == 640, ...
    'The complete matrix must represent 640 injection runs.');
assert(nnz(studyResult.reused_phase3_mask) == 4 && ...
    all(studyResult.reused_phase3_mask(:,2)), ...
    'Exactly the four nominal-PLL cases must reuse stage-three results.');
assert(studyResult.reused_injection_runs == 160 && ...
    studyResult.new_injection_runs == 480, ...
    'Run accounting must separate reused and new injections.');
assert(all(isfinite(studyResult.peak_interaction_gain),'all') && ...
    all(studyResult.peak_interaction_gain >= 0,'all'), ...
    'The peak interaction matrix contains an invalid value.');
assert(all(isfinite(studyResult.critical_frequency_Hz),'all') && ...
    all(studyResult.critical_frequency_Hz >= 0.5,'all') && ...
    all(studyResult.critical_frequency_Hz <= 100,'all'), ...
    'A critical frequency is outside the scan range.');

expectedRiskCode = ones(4,4);
expectedRiskCode(studyResult.peak_interaction_gain >= ...
    studyResult.thresholds.moderate) = 2;
expectedRiskCode(studyResult.peak_interaction_gain >= ...
    studyResult.thresholds.higher) = 3;
assert(isequal(studyResult.risk_code, expectedRiskCode), ...
    'A risk-map cell is inconsistent with the fixed thresholds.');

nominalControl = ...
    studyResult.cases(1,2).scan.configuration.controller_configuration;
nominalKp = nominalControl.pllKp;
nominalKi = nominalControl.pllKi;
allowedLevels = ["Lower" "Moderate" "Higher"];
for row = 1:numel(studyResult.scr_values)
    for column = 1:numel(studyResult.pll_scales)
        item = studyResult.cases(row,column);
        scale = studyResult.pll_scales(column);
        configuration = item.scan.configuration;
        assert(all(item.scan.completed), 'A matrix scan is incomplete.');
        assert(abs(configuration.scr-item.scr) <= 1e-12 && ...
            abs(configuration.pll_scale-scale) <= 1e-12, ...
            'A scan configuration does not match its matrix coordinates.');
        assert(abs(configuration.controller_configuration.pllKp - ...
            nominalKp*scale) <= 1e-10 && ...
            abs(configuration.controller_configuration.pllKi - ...
            nominalKi*scale) <= 1e-8, ...
            'PLL gains are inconsistent with the requested scale.');
        assert(all(isfinite(real(item.scan.Y_dq_S)),'all') && ...
            all(isfinite(imag(item.scan.Y_dq_S)),'all'), ...
            'A dq admittance contains non-finite values.');
        assert(all(item.scan.voltage_matrix_condition < ...
            configuration.maximum_voltage_matrix_condition), ...
            'A scan contains an ill-conditioned voltage matrix.');
        assert(all(item.scan.maximum_fault_state < 0.5), ...
            'A scan unexpectedly activated the physical fault.');
        assert(all(item.scan.minimum_soc_pu > 0.10) && ...
            all(item.scan.maximum_soc_pu < 0.90), ...
            'A scan left the configured SoC operating band.');
        assert(any(studyResult.risk_level(row,column) == allowedLevels), ...
            'A matrix cell contains an unrecognized risk level.');
    end
end

fprintf(['PHASE 4 PLL RISK MAP CHECK PASS | %d cases | ' ...
    '%d represented injection runs\n'], numel(studyResult.cases), ...
    studyResult.total_matrix_injection_runs);
for row = 1:numel(studyResult.scr_values)
    fprintf('  SCR %g | peak gains:', studyResult.scr_values(row));
    fprintf(' %.6g', studyResult.peak_interaction_gain(row,:));
    fprintf('\n');
end
