% RUN_PHASE2_FREQUENCY_SCAN_CHECK Verify the complete nominal dq scan.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'scripts'));
resultFile = fullfile(projectRoot, 'results', 'phase2_frequency_scan.mat');
if ~isfile(resultFile)
    run_frequency_scan([], resultFile);
end
saved = load(resultFile, 'scanResult');
scanResult = saved.scanResult;

assert(numel(scanResult.frequency_Hz) == 20, ...
    'The nominal scan must contain 20 frequency points.');
assert(abs(scanResult.frequency_Hz(1)-0.5) < 1e-12 && ...
    abs(scanResult.frequency_Hz(end)-100) < 1e-12, ...
    'The nominal scan must cover 0.5 to 100 Hz.');
assert(all(scanResult.completed), 'At least one frequency point is incomplete.');
assert(all(isfinite(real(scanResult.Y_dq_S)), 'all') && ...
    all(isfinite(imag(scanResult.Y_dq_S)), 'all'), ...
    'The identified dq admittance contains non-finite values.');
assert(all(scanResult.voltage_matrix_condition < ...
    scanResult.configuration.maximum_voltage_matrix_condition), ...
    'At least one frequency point has an ill-conditioned voltage matrix.');
assert(all(scanResult.maximum_fault_state < 0.5), ...
    'A frequency-scan injection unexpectedly activated the physical fault.');
assert(all(scanResult.minimum_soc_pu > 0.10) && ...
    all(scanResult.maximum_soc_pu < 0.90), ...
    'A frequency-scan injection left the configured SoC operating band.');
fprintf('PHASE 2 FREQUENCY SCAN CHECK PASS | %d points | %d injection runs\n', ...
    numel(scanResult.frequency_Hz), 2*numel(scanResult.frequency_Hz));
