% RUN_PHASE1_INTERFACE_CHECK Verify the single-frequency interface result.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
resultFile = fullfile(projectRoot, 'results', 'phase1_single_frequency_demo.mat');
needsRun = ~isfile(resultFile);
if ~needsRun
    saved = load(resultFile, 'phase1_result');
    needsRun = ~isfield(saved.phase1_result, 'fit_quality') || ...
        ~isfield(saved.phase1_result.fit_quality, ...
        'current_matrix_weighted_residual');
end
if needsRun
    run(fullfile(projectRoot, 'scripts', 'run_single_frequency_demo.m'));
end
load(resultFile, 'phase1_result');

assert(isfinite(phase1_result.summary.d_axis_delta_vd_peak_to_peak_V) && ...
    phase1_result.summary.d_axis_delta_vd_peak_to_peak_V > 5, ...
    'The d-axis injection did not create a measurable PCC d-axis voltage response.');
assert(isfinite(phase1_result.summary.q_axis_delta_vq_peak_to_peak_V) && ...
    phase1_result.summary.q_axis_delta_vq_peak_to_peak_V > 5, ...
    'The q-axis injection did not create a measurable PCC q-axis voltage response.');
assert(abs(phase1_result.summary.baseline_pll_frequency_mean_Hz - 50) < 0.5, ...
    'The baseline PLL frequency is outside the nominal verification band.');
assert(phase1_result.summary.maximum_fault_state < 0.5, ...
    'A small-signal interface test unexpectedly activated the physical fault.');
assert(phase1_result.summary.minimum_soc_pu > 0.10 && ...
    phase1_result.summary.maximum_soc_pu < 0.90, ...
    'A small-signal interface test left the configured SoC operating band.');
quality = phase1_result.fit_quality;
assert(quality.main_voltage_passed, ...
    'A main injected voltage channel exceeds the fixed fit-residual limit.');
assert(quality.current_response_passed, ...
    'The current-response matrix exceeds the weighted fit-residual limit.');
assert(quality.reference_current_all_channels_passed, ...
    'A 10 Hz current channel exceeds the reference raw-residual limit.');
assert(quality.cross_voltage_leakage_passed, ...
    'A cross-voltage leakage ratio exceeds the fixed limit.');
assert(~quality.cross_voltage_residual_is_acceptance_metric, ...
    'A near-zero cross-voltage residual must remain report-only.');
assert(quality.passed, 'The 10 Hz identification quality gate failed.');
fprintf(['PHASE 1 INTERFACE CHECK PASS | main voltage residual %.4g | ' ...
    'weighted current residual %.4g | raw current residual %.4g | ' ...
    'cross leakage %.4g\n'], ...
    quality.maximum_main_voltage_relative_residual, ...
    quality.maximum_current_matrix_weighted_residual, ...
    quality.raw_maximum_current_relative_residual, ...
    quality.maximum_cross_voltage_leakage_ratio);
