function quality = assess_frequency_scan_fit_quality(point, thresholds)
%ASSESS_FREQUENCY_SCAN_FIT_QUALITY Apply fixed identification quality gates.

requiredFields = {'main_voltage_relative_residual', ...
    'current_matrix_weighted_residual', ...
    'reference_current_relative_residual', ...
    'cross_voltage_leakage_ratio'};
for k = 1:numel(requiredFields)
    name = requiredFields{k};
    if ~isfield(thresholds, name)
        error('FrequencyScan:FitQualityThreshold', ...
            'The fit-quality threshold %s is missing.', name);
    end
    validateattributes(thresholds.(name), {'numeric'}, ...
        {'real','finite','positive','scalar'}, mfilename, name);
end

residual = point.relative_fit_residual;
voltage = point.voltage_phasor_V;
mainVoltageResidual = [residual(1,1), residual(2,2)];
crossVoltageResidual = [residual(2,1), residual(1,2)];
currentResidual = residual(3:4,:);
currentMagnitude = abs(point.current_phasor_A);
currentMagnitudeRatio = currentMagnitude / ...
    max(max(currentMagnitude, [], 'all'), eps);
currentWeightedResidual = currentResidual.*currentMagnitudeRatio;
crossVoltageLeakage = [ ...
    abs(voltage(2,1))/max(abs(voltage(1,1)), eps), ...
    abs(voltage(1,2))/max(abs(voltage(2,2)), eps)];

quality = struct();
quality.main_voltage_relative_residual = mainVoltageResidual;
quality.cross_voltage_relative_residual_report_only = ...
    crossVoltageResidual;
quality.current_relative_residual = currentResidual;
quality.current_tone_magnitude_A = currentMagnitude;
quality.current_tone_magnitude_ratio = currentMagnitudeRatio;
quality.current_matrix_weighted_residual = currentWeightedResidual;
quality.cross_voltage_leakage_ratio = crossVoltageLeakage;
quality.maximum_main_voltage_relative_residual = max(mainVoltageResidual);
quality.maximum_current_matrix_weighted_residual = ...
    max(currentWeightedResidual, [], 'all');
quality.raw_maximum_current_relative_residual = ...
    max(currentResidual, [], 'all');
quality.maximum_cross_voltage_leakage_ratio = max(crossVoltageLeakage);
quality.raw_maximum_relative_residual = max(residual, [], 'all');
quality.thresholds = thresholds;
quality.main_voltage_passed = ...
    quality.maximum_main_voltage_relative_residual <= ...
    thresholds.main_voltage_relative_residual;
quality.current_response_passed = ...
    quality.maximum_current_matrix_weighted_residual <= ...
    thresholds.current_matrix_weighted_residual;
quality.reference_current_all_channels_passed = ...
    quality.raw_maximum_current_relative_residual <= ...
    thresholds.reference_current_relative_residual;
quality.cross_voltage_leakage_passed = ...
    quality.maximum_cross_voltage_leakage_ratio <= ...
    thresholds.cross_voltage_leakage_ratio;
quality.passed = quality.main_voltage_passed && ...
    quality.current_response_passed && ...
    quality.cross_voltage_leakage_passed;
quality.cross_voltage_residual_is_acceptance_metric = false;
end
