function value = frequency_scan_case_signature(scanCfg)
%FREQUENCY_SCAN_CASE_SIGNATURE Build a stable scan-configuration identity.

quality = scanCfg.fit_quality_thresholds;
value = sprintf(['SCR=%.12g|PLL=%.12g|SBASE=%.12g|XR=%.12g|' ...
    'FIT=%d|VR=%.12g|IW=%.12g|IR=%.12g|XL=%.12g'], ...
    scanCfg.scr, scanCfg.pll_scale, scanCfg.converter_base_power_VA, ...
    scanCfg.grid_xr_ratio, scanCfg.fit_quality_schema_version, ...
    quality.main_voltage_relative_residual, ...
    quality.current_matrix_weighted_residual, ...
    quality.reference_current_relative_residual, ...
    quality.cross_voltage_leakage_ratio);
end
