% INIT_PHASE2 Parameters for the Phase 2 grid-following control layer.

init_phase1;

% Operator set-points. Positive P/Q follow the controller's dq convention.
P_ref_W = 100e3;
Q_ref_var = 0;
Vdc_ref_V = Vdc_test_V;

% Optional in-model P/Q step injection.  Keeping the default amplitudes at
% zero preserves nominal operation; regression tests override them through
% SimulationInput to verify dynamic tracking without rewiring the model.
p_step_time_s = 0.05;
q_step_time_s = 0.05;
p_step_amplitude_W = 0;
q_step_amplitude_var = 0;

ctrl_sample_time_s = 50e-6;
ctrl_cfg = struct( ...
    'sampleTime_s', ctrl_sample_time_s, ...
    'wNom_rad_s', w_grid_rad_s, ...
    'wMin_rad_s', 2*pi*45, ...
    'wMax_rad_s', 2*pi*55, ...
    'pllKp', 180, ...
    'pllKi', 1.2e4, ...
    'pllIntLimit', 2*pi*10, ...
    'vEnable_V', 1e3, ...
    'vFloor_V', 1e3, ...
    'vdcFloor_V', 1e3, ...
    'vdcKp_W_per_V', 100, ...
    'vdcKi_W_per_Vs', 1e3, ...
    'pLimit_W', 500e3, ...
    'qLimit_var', 300e3, ...
    'iLimit_A', 150, ...
    'rEq_Ohm', R1_Ohm + R2_Ohm, ...
    'lEq_H', L1_H + L2_H, ...
    'currentKp_V_per_A', 8, ...
    'currentKi_V_per_As', 800, ...
    'vCmdLimit_V', 0.95 * Vdc_test_V / 2, ...
    'mLimit', 0.95, ...
    'modulationPolarity', 1, ...
    'mBase', 0.85);
