function in = make_time_domain_validation_input(caseConfig, validationCfg, ...
    scanCfg, modelName, modelVariables)
%MAKE_TIME_DOMAIN_VALIDATION_INPUT Configure one non-destructive step run.

validateattributes(caseConfig.scr, {'numeric'}, ...
    {'real','finite','positive','scalar'}, mfilename, 'caseConfig.scr');
validateattributes(caseConfig.pll_scale, {'numeric'}, ...
    {'real','finite','positive','scalar'}, mfilename, ...
    'caseConfig.pll_scale');
validateattributes(validationCfg.stop_time_s, {'numeric'}, ...
    {'real','finite','positive','scalar'}, mfilename, ...
    'validationCfg.stop_time_s');
if validationCfg.step_time_s <= 0 || ...
        validationCfg.step_time_s >= validationCfg.stop_time_s
    error('TimeDomainValidation:StepTime', ...
        'The step time must lie strictly inside the simulation interval.');
end

control = scanCfg.controller_configuration;
control.pllKp = control.pllKp*caseConfig.pll_scale;
control.pllKi = control.pllKi*caseConfig.pll_scale;

in = Simulink.SimulationInput(modelName);
variableNames = fieldnames(modelVariables);
for k = 1:numel(variableNames)
    name = variableNames{k};
    in = in.setVariable(name, modelVariables.(name));
end
in = in.setModelParameter('StopTime', ...
    num2str(validationCfg.stop_time_s, '%.12g'));
in = in.setVariable('P_ref_initial_W', ...
    validationCfg.initial_active_power_W);
in = in.setVariable('P_ref_final_W', ...
    validationCfg.final_active_power_W);
in = in.setVariable('Q_ref_initial_var', ...
    validationCfg.reactive_power_var);
in = in.setVariable('Q_ref_final_var', ...
    validationCfg.reactive_power_var);
in = in.setVariable('case_step_time_s', validationCfg.step_time_s);
in = in.setVariable('S_sc_grid_VA', ...
    caseConfig.scr*scanCfg.converter_base_power_VA);
in = in.setVariable('X_R_grid', scanCfg.grid_xr_ratio);
in = in.setVariable('ctrl_cfg', control);
in = in.setBlockParameter(scanCfg.pcc_source_block, ...
    'magnitude_type', 'ee.enum.timechanging.constant');
in = in.setBlockParameter(scanCfg.pcc_source_block, ...
    'phase_type', 'ee.enum.timechanging.constant');
end
