function scanResult = reassess_frequency_scan_quality(scanResult, scanCfg)
%REASSESS_FREQUENCY_SCAN_QUALITY Apply current gates to saved raw metrics.

requiredFields = { ...
    'completed', ...
    'maximum_main_voltage_fit_residual', ...
    'maximum_current_weighted_fit_residual', ...
    'maximum_cross_voltage_leakage_ratio'};
for k = 1:numel(requiredFields)
    if ~isfield(scanResult, requiredFields{k})
        error('FrequencyScan:QualityMetricsMissing', ...
            'Saved scan is missing quality metric "%s".', requiredFields{k});
    end
end
if ~all(scanResult.completed)
    error('FrequencyScan:IncompleteQualityReassessment', ...
        'Quality gates can be reassessed only after every point is complete.');
end

limits = scanCfg.fit_quality_thresholds;
scanResult.fit_quality_passed = ...
    scanResult.maximum_main_voltage_fit_residual <= ...
        limits.main_voltage_relative_residual & ...
    scanResult.maximum_current_weighted_fit_residual <= ...
        limits.current_matrix_weighted_residual & ...
    scanResult.maximum_cross_voltage_leakage_ratio <= ...
        limits.cross_voltage_leakage_ratio;
scanResult.configuration.fit_quality_schema_version = ...
    scanCfg.fit_quality_schema_version;
scanResult.configuration.fit_quality_thresholds = limits;
scanResult.case_signature = ...
    frequency_scan_case_signature(scanResult.configuration);
scanResult.quality_reassessed_utc = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss''Z'''));
end
